import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './components/footer'
import Header from './components/header/header'
import Whatsapp from './components/whatsapp'
import "bootstrap-icons/font/bootstrap-icons.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DEP sac',
  description: 'Generated by RahamsisCG.',
  icons: '/faviconDepsac.ico',
  openGraph: {
    title: 'DEPSAC ',
    description: 'Diseño de equipos y proyectos',
    url: 'https://depsac.com.pe',
    images: [
      {
        url: '/depsac_miniatura.png',
        width: 1200,
        height: 630,
        alt: 'Imagen de vista previa',
      },
    ],
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'DEP sac',
    description: 'Diseño de equipos y proyectos',
    images: ['public/depsac_miniatura.png'],
  },
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {

  

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
        <Whatsapp />
      </body>
    </html>
  )
}
