import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './components/footer'
import Header from './components/header/header'
import Whatsapp from './components/whatsapp'
import "bootstrap-icons/font/bootstrap-icons.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DEP sac',
  description: 'Generated by RahamsisCG.',
  icons: '/faviconDepsac.ico',
  openGraph: {
    title: 'DEPSAC ',
    description: 'Diseño de equipos y proyectos',
    url: 'https://depsac.com.pe',
    images: [
      {
        url: 'https://depsac.com.pe/depsac_miniatura.png',
        width: 1200,
        height: 630,
        alt: 'Imagen de vista previa',
      },
    ],
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'DEP sac',
    description: 'Diseño de equipos y proyectos',
    images: ['https://depsac.com.pe/depsac_miniatura.png'],
  },
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {



  return (
    <html lang="en">
      <head>
        {/* Etiquetas meta adicionales para compartir correctamente */}
        <meta property="og:title" content="DEPSAC" />
        <meta property="og:description" content="Diseño de equipos y proyectos" />
        <meta property="og:image" content="https://depsac.com.pe/depsac_miniatura.png" />
        <meta property="og:url" content="https://depsac.com.pe" />
        <meta property="og:type" content="website" />

        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="DEP sac" />
        <meta name="twitter:description" content="Diseño de equipos y proyectos" />
        <meta name="twitter:image" content="https://depsac.com.pe/depsac_miniatura.png" />
        <link rel="icon" href="/faviconDepsac.ico" />
      </head>
      <body className={inter.className}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
        <Whatsapp />
      </body>
    </html>
  )
}
